name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: cp .env.example .env
      - run: npm ci
      - name: "npm CI test"
        run: |
          # sometimes not created and is not tailed
          touch fhevm.log
          npm run fhevm:start &> fhevm.log &
          tail -f fhevm.log | sed '/Starting JSON WebSocket server/ q'
          npm run test:inband
          npm run fhevm:stop || true
